### ISSUE TITLE
500 Internal Server Error: injection from VCAP_SERVICES not working

### ISSUE THREAD

**Issue by gssales** [SAP-samples/cloud-objectstore-java-sample#14]
Hi, I keep getting the same 500 error when I send a request to the service. 

This is the response I get

```{
  "timestamp": "2021-12-14T14:38:37.085+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "identity",
  "path": "/objectstorage.svc/api/v1/storage"
}
```

On the logs I can see that some value that should be mapped from the VCAP_SERVICES is giving a NullPointerException.

```
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT 2021-12-14 14:38:37.076 ERROR 8 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: identity] with root cause
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: identity
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-27.1-jre.jar:na]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.jclouds.ContextBuilder.credentials(ContextBuilder.java:259) ~[jclouds-core-2.3.0.jar:2.3.0]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at com.sap.refapps.objectstore.config.AmazonWebServiceConfiguration.getBlobStoreContext(AmazonWebServiceConfiguration.java:49) ~[classes/:na]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at com.sap.refapps.objectstore.service.AWSObjectStoreService.listObjects(AWSObjectStoreService.java:43) ~[classes/:na]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at com.sap.refapps.objectstore.controller.ObjectstoreController.listFiles(ObjectstoreController.java:54) ~[classes/:na]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
   2021-12-14T14:38:37.07+0000 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.3.RELEASE.jar:5.2.3.RELEASE]
[...]
```

I did change the name of the objectstore service that the app uses on manifest.yml and on AmazonWebServiceConfiguration.java, but it still gives the same error

manifest.yml

```
---
applications:
- name: test-objectstore-svc
  host: test-objectstore-svc
  memory: 1G
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  path: target/objectstore-sample-1.0.0.jar
  services:
    - test-objectstore
```

AmazonWebServiceConfiguration.java

```java
/**
 * This is AWS Credentials Configuration class
 *
 */

@Profile("cloud-aws")
@Configuration
@ConfigurationProperties(prefix = "vcap.services.test-objectstore.credentials")
public class AmazonWebServiceConfiguration {
	...
```

I also checked and the objectstore instance exists and is binded to the app

![image](https://user-images.githubusercontent.com/42186318/146023243-5f1c229d-d2d5-431e-a84e-2db788be3768.png)

I don't see why it is not working? Did I miss something?

**Comment by gssales** [comment]
Nevermind, found the solution
